// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Library.Infrastructure.Persistence.Context;
// Pomelo MySQL infrastructure using removed for compatibility with resolved package version

#nullable disable

namespace Library.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251207184120_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Auto-increment configuration removed for compatibility

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                // UseMySqlIdentityColumn removed for compatibility

                b.Property<string>("Author")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<string>("ISBN")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("varchar(200)");

                b.Property<int>("Stock")
                    .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("ISBN")
                    .IsUnique();

                b.ToTable("Books", (string)null);
            });

                modelBuilder.Entity("Library.Domain.Entities.ArticuloBaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId").HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("tb_articulos_baja", (string)null);
                });

                modelBuilder.Entity("Library.Domain.Entities.ArticuloLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BookId").HasColumnType("int");

                    b.Property<int>("Quantity").HasColumnType("int");

                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("tb_articulos_liquidacion", (string)null);
                });

            modelBuilder.Entity("Library.Domain.Entities.Loan", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                // UseMySqlIdentityColumn removed for compatibility with resolved Pomelo package version

                b.Property<int>("BookId")
                    .HasColumnType("int");

                b.Property<string>("StudentName")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<DateTime>("LoanDate")
                    .HasColumnType("datetime(6)");

                b.Property<DateTime?>("ReturnDate")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("BookId");

                b.HasIndex("Status");

                b.ToTable("Loans", (string)null);
            });

            modelBuilder.Entity("Library.Domain.Entities.Loan", b =>
            {
                b.HasOne("Library.Domain.Entities.Book")
                    .WithMany("Loans")
                    .HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

#pragma warning restore 612, 618
        }
    }
}
